//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttencandeSystemWebApp {
	using System;
	using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations.Schema;

	public partial class StudentCourse {
		public int rollno { get; set; }
		public string name { get; set; }
		public Nullable<int> @class { get; set; }
		public string subject { get; set; }
		[NotMapped]
		public string isPresent { get; set; }
	}
}
