//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttencandeSystemWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendance
    {
        public int rollno { get; set; }
        public string subject { get; set; }
        public string present { get; set; }
        public System.DateTime date { get; set; }
    }
}
